export const SUUQ_LIST_REQ = "SUUQ_LIST_REQ";
export const SUUQ_LIST_SUCCESS = "SUUQ_LIST_SUCCESS";
export const SUUQ_LIST_FAIL = "SUUQ_LIST_FAIL";

export const SUUQ_DETAILS_REQ = "SUUQ_DETAILS_REQ";
export const SUUQ_DETAILS_SUCCESS = "SUUQ_DETAILS_SUCCESS";
export const SUUQ_DETAILS_FAIL = "SUUQ_DETAILS_FAIL";
